# Generated by Django 5.2.4 on 2025-07-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0002_question_constraints_question_cpp_starter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='solution',
            field=models.TextField(blank=True, help_text='Editorial solution explanation'),
        ),
    ]
